### ISSUE TITLE
AWR1243 WITHOUT  DEVPACK , LUNCHPAD

### ISSUE THREAD

**Issue by 9309191** [radar-lab/TI-mmwave-RADAR#1]
HI, I'm University student. 

I am studing radar with AWR1243BOOST.

but I couldn't get a data. Because TI doesn't operate Demo for AWR1243BOOST.
So, I searched at the GitHub about AWR1243.
and I found your AWR1243 Code.

so, I ask to you "can I use AWR1243BOOST without DEVPACK, LUNCHPAD?
and I want to know What is meaning of your code file in the Ti-mmwave-RADAR folder?

Thank you.

**Comment by zrmaker** [comment]
Hi,

We have conduct a real-time monitoring using awr1243, devpack and the TSW1400. 

AWR1243boost does not provide a capturing and sending data feature. Thus you need ADC and memory to send data to pc. So TSW1400 is used. However, TSW1400 cannot directly connect to AWR1243. So you need the devpack for connection. If you only use AWR1243, you may only try some samples on TI website. Or, you can get a awr1443 for complete data collection.

Regards,
Leo

**Comment by 9309191** [comment]
Thanks Leo! 

but, I couldn't find samples for AWR1243..at the TI website.
If you know samples link, Could you give to me the Link?

**Comment by zrmaker** [comment]
You may refer to radar studio provided by TI (http://www.ti.com/tool/mmwave-studio)

Leo

**Comment by 9309191** [comment]
Thank you! 

Hun.K
